name: gdedcinc
favicon: null
layout_spectrum: 0.9478529973421246
typography_spectrum: 0.03399699227884412
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1c2c65'
    - '#000000'
    - '#8a0031'
    - '#cecece'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
